###  config/payloads.yaml ###

### single_header_dinamic
single_header_dinamic:
    - header: "Host"
      value: "%h"

    - header: "X-Forwarded-Host"
      value: "%h"

    - header: "X-Forwarded-For"
      value: "%i, %m"

    - header: "X-Real-IP"
      value: "%m"

    - header: "Referer"
      value: "http://%h/%m"

    - header: "Origin"
      value: "https://%h"

    - header: "X-Forwarded-Proto"
      value: "%m"

    - header: "X-Original-URL"
      value: "/%m"

    - header: "X-Rewrite-URL"
      value: "/%m"

    - header: "X-Forwarded-Server"
      value: "%h"

    - header: "User-Agent"
      value: "Mozilla/5.0 (%m)"

    - header: "X-Request-ID"
      value: "%m"

    - header: "X-Api-Key"
      value: "%m"

    - header: "X-Access-Token"
      value: "%m"

    - header: "X-Foo"
      value: "%m"

    - header: "Cookie"
      value: "session=%m"

    - header: "X-Origin"
      value: "%h"

    - header: "X-Http-DestinationURL"
      value: "http://%h/payload.js"

    - header: "X-Custom-Trace"
      value: "%m"

    - header: "X-Original-Host"
      value: "%h"

    - header: "Forwarded"
      value: "for=%h;proto=http"

    - header: "X-Forwarded"
      value: "for=%h;proto=http"

    - header: "Alt-Used"
      value: "%h:%p"

    - header: "X-Amz-Website-Redirect-Location"
      value: "http://%h/%m"

    - header: "X-Client-IP"
      value: "%m"

    - header: "X-Request-Signature"
      value: "%m"

    - header: "X-Ua-Device"
      value: "%m"

    - header: "X-Wap-Profile"
      value: "http://%h/profile.xml"

    - header: "True-Client-IP"
      value: "%m"

    - header: "X-Prototype-Version"
      value: "%m"

    - header: "X-Elgg-Hmac"
      value: "%m"

    - header: "X-Invoke-Output"
      value: "%m"

    - header: "Slug"
      value: "%m"

    - header: "X-Requested-With"
      value: "%m"
#     - header: "X-Forwarded-Ssl"
#       value: "on"
